# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 02:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birday',
            field=models.DateField(default=datetime.datetime.now, verbose_name='生日'),
        ),
    ]
