# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-11 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(default='', max_length=300, verbose_name='视频链接'),
        ),
    ]
