# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-11 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_video_learn_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher_tell',
            field=models.CharField(default='', max_length=300, verbose_name='老师告诉'),
        ),
        migrations.AddField(
            model_name='course',
            name='your_need',
            field=models.CharField(default='', max_length=300, verbose_name='课程须知'),
        ),
    ]
