# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-11 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_teacher_image'),
        ('courses', '0009_auto_20180311_1557'),
    ]


