# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-21 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='id_banner',
            field=models.BooleanField(default=False, verbose_name='是否轮播'),
        ),
    ]
