# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-21 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_course_id_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='id_banner',
        ),
    ]
