# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-01 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20180228_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='tearch/%Y/%m', verbose_name='教师照片'),
        ),
    ]
