# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-21 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_teacher_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='org_tag',
            field=models.CharField(default='全国知名', max_length=10, verbose_name='标签'),
        ),
    ]
